import os from 'node:os'; import fs from 'node:fs'; import path from 'node:path';
const R = 'file:///C:/projects/quereus/packages/';
const { Database } = await import(R + 'quereus/dist/src/index.js');
const { createIsolatedStoreModule } = await import(R + 'quereus-store/dist/src/index.js');
const { createLevelDBProvider } = await import(R + 'quereus-plugin-leveldb/dist/src/index.js');
const dir = path.join(os.tmpdir(), `probe-store-${Date.now()}`);
fs.mkdirSync(dir, { recursive: true });
const db = new Database();
db.registerModule('store', createIsolatedStoreModule({ provider: createLevelDBProvider({ basePath: dir.split(path.sep).join('/') }) }));
db.setOption('default_vtab_module', 'store');
const q = async (sql) => { const rows = []; for await (const r of db.eval(sql)) rows.push(r); return rows; };
const show = async (l, sql) => { try { console.log(l.padEnd(28), JSON.stringify(await q(sql))); } catch (e) { console.log(l.padEnd(28), 'ERR ' + e.message); } };
await db.exec(`create table il (d timespan primary key)`);
await db.exec(`insert into il values ('PT2H'), ('PT90M')`);
await show('all', `select d from il`);
await show('eq exact', `select d from il where d = 'PT2H'`);
await show('eq equiv', `select d from il where d = 'PT120M'`);
await show('in-list', `select d from il where d in ('PT120M','PT30M')`);
await show('in-list exact', `select d from il where d in ('PT2H','PT30M')`);
await show('or form', `select d from il where d = 'PT120M' or d = 'PT30M'`);
console.log('plan in-list:');
for await (const r of db.eval(`explain query plan select d from il where d in ('PT120M','PT30M')`)) console.log('  ', JSON.stringify(r).slice(0, 300));
await db.close();
fs.rmSync(dir, { recursive: true, force: true });
